### ISSUE TITLE
make a param.yaml file for user configurations

### ISSUE THREAD

**Issue by arnaudon** [ImperialCollegeLondon/hcga#14]

**Comment by arnaudon** [comment]
we may not need that in the end, we can pass all options via the app

**Comment by nrbernier** [comment]
I agree that it might not be necessary. I support the idea of passing an option `--custom-features [file]` so that the user can directly write the list of feature class they want in a file.

**Comment by arnaudon** [comment]
we could have a .yaml file like:
`feature_class_name: True
feature_class_name2: False`

**Comment by nrbernier** [comment]
But that requires a lot of work for the user. If the custom-features file is just a list of the feature module names, then making it just requires dumping the output of `ls` to a file and removing the ones that are unwanted. Or just copy/pasting things around

**Comment by arnaudon** [comment]
indeed, you option may be easier. Or we provide a list of feature class, and people just go through it and unselect the one they don't want, not sure what is better. Try something if you have time, we can still update later if we find a better option!

**Comment by arnaudon** [comment]
Ok. let's not do that, I'll close this issue
