### ISSUE TITLE
Simplifying file inputs for app.py commands

### ISSUE THREAD

**Issue by nrbernier** [ImperialCollegeLondon/hcga#17]
I thought it would be simpler to have the argument of the commands directly be the pickled file to load. As it is, both `extract_features` and `feature_analysis` require to specify both a folder name and a name of the dataset (without any naming extension, as the io.py function later adds `.pkl` by hand).

Wouldn't it be easier and more straightforward to let the user specify the dataset (with its extension) at any path? Then one can use automatic completion in the terminal to add the file. 

If other people agree I can implement it.

**Comment by arnaudon** [comment]
agree!
