### ISSUE TITLE
Variability in output of SHAP

### ISSUE THREAD

**Issue by nrbernier** [ImperialCollegeLondon/hcga#20]
I was playing around running multiple times the SHAP analysis on the same feature matrix. I noticed that there is some slight variation in the order of the SHAP values listed in terms of importance. There is also a variation in the "balanced accuracy". It's almost always the exact same number but sometimes it's off (0.86 instead of 0.90 for instance).

I guess that it depends on the training of the classifier and maybe on the way the SHAP values are computed, which requires some kind of sampling as I vaguely understand. Anyway one might want to look into it.

**Comment by arnaudon** [comment]
Is this because the seed is not fixed? Each time it selects a different split of the data? We could have an option to fix the seed for testing purposes. @peach-lucien was saying that people in ML try to find a seed that gives the highest accuracies... such a joke!

**Comment by peach-lucien** [comment]
Yes this should become consistent with fixed seed. We can fix this to make our life more simple.

Balanced accuracy is more likely to be affected by random seed. The difference between folds when there are unbalanced classes becomes more evident.
