### ISSUE TITLE
User experience for feature analysis

### ISSUE THREAD

**Issue by nrbernier** [ImperialCollegeLondon/hcga#21]
I wanted to launch a discussion on how we would like the main command(s) of hcga to look like, before we go in multiple directions.

Currently there are two commands, `feature_analysis` and `plot_analysis` to do the classification of the graphs and plot it. Does it make sense to have a separate `plot_analysis` command? Do we want to give tons of different options for plotting to the user so that they will want to run in multiple times? In my view it is probably not necessary. As I understand it, the user would run the main classification once and then can look at some standard plot produced. They would do their own plotting if they want something that looks different. They might play with the settings of the classification, but then it would anyway have to run many times and producing the plots is not the computationally expensive part.

Another aspect is that it is currently a single command that takes as an option the kind of analysis to be done, either straight classification with sklearn or with shap values. As I understand it the SHAP analysis just computes the values on top of doing the same exact training of the random forrest or boost, so it does not change things that much. But there is the option of doing two different commands if we feel that the analysis is very different.

I would like to have a feel as to what the end goal is in terms of user experience. What do we want the user to be able to do and what kind of data do they want at the end to be able to look at?

For instance, while the user does not need to look at the initial dataset, they might want to have a look in the features extracted and the analysis results with some other programs. It might be interesting to save the relevant data as text files instead of python pickles then.

**Comment by arnaudon** [comment]
This is indeed an important point! What about that:

- we merge both commands in one
- this command will save the following things:
     - the feature_matrix dataframe (so experienced users can use it as they want)
     - the feature_info dict (to go with the dataframe maybe) (we could use hdf5 file format to put both together)
     - basic sklearn plots in a subfolder (always created)
     - more advanced shap plots if shap is enabled (there is a way to pip install with shap as an option, like in this setup.py for plotly: https://github.com/BlueBrain/NeuroM/blob/master/setup.py)

In this way, we reduce user options to a minimum. Now we need to decide which plot to save, and which format, html, or .svg/,png, etc... If it is fast, we can do all and save them in subfolders with easy to understand names.

**Comment by peach-lucien** [comment]
The feature matrix should have the option to be saved as csv that can be read by other programs.

We should directly incorporate the plotting into the analysis i.e. no need for another function in the app.py . We can keep plotting.py and just load the functions that we want directly into analyse.py

The user should be able to compute_shap=True and we will compute shap values and also plot=True and the analysis module will also produce the plots.

**Comment by peach-lucien** [comment]
Okay I have made some updates to get basic plotting and analysis. I will continue to work on this this week. 

I removed plotting from app.py and now you just have a --plot flag in analysis. Still need to set it up to save plots etc. There is now also a --shap flag in the analysis. We don't really need to save the shap results for now either.

**Comment by nrbernier** [comment]
Sounds good to pack plotting together. 

It would also be nice to output the feature description as text files so that they can be read easily by the users.

**Comment by nrbernier** [comment]
I put a few small changes to command options in #25.

**Comment by arnaudon** [comment]
Is this kind of sorted now? We just have a single analysis function that produces plots, and a .csv file with all the outputs.
