### ISSUE TITLE
Plot styles and feature readability

### ISSUE THREAD

**Issue by nrbernier** [ImperialCollegeLondon/hcga#22]
There was a mention earlier of implementing the plots with plotly such that one could hover over the data points and get detailed information about the features (using the descriptions). Is that something that we want to get into? Plots could be saved as html files for instance, which gives this option to hover later on.

I'm not sure if it is possible to change the plotting library when plotting using the functions in `shap`. It might not be possible and then maybe not worth it to fight too much over the default. What do you think?

**Comment by arnaudon** [comment]
I don't really know, but it seems that shap provides html plots as well, similar to what we could get with plotly. Maybe we just want a 'standard' analysis with sklearn and matplotlib, and a more advanced one, based on shap, and using there plotting functions. Not sure it'll be worth adding plotly to the 'standard' analysis, if shap is good enough for what we want, we'll stick to it most of the time. 

So  maybe let's explore the possibilities with shap, and then we decide!

**Comment by peach-lucien** [comment]
i still think its valid to create plotly type figures, but for now i'll close this issue because we have produced a number of decent plots that aren't interactive.
