### ISSUE TITLE
how to use interpretability score in analysis?

### ISSUE THREAD

**Issue by arnaudon** [ImperialCollegeLondon/hcga#23]
no sure how using shap?

**Comment by arnaudon** [comment]
so we will use this as a feature filter before running any analysis. 
We could output several analysis, one for each level of feature interpretability

**Comment by peach-lucien** [comment]
yes I can now make sure the analysis is done for different levels of interpretability as an input. I'll get onto this this weekk

**Comment by arnaudon** [comment]
it works, thanks!
