### ISSUE TITLE
Feature class add_feature

### ISSUE THREAD

**Issue by peach-lucien** [ImperialCollegeLondon/hcga#26]
The add_feature is setup so that if an error in calling a function occurs it return nan. However, sometimes we want to compute multiple things from a single function e.g. I compute the community structure using asynfluid and from that output I will create 5 or 6 features. I can't put the computation of the community structure directly into add_feature for each separate feature because otherwise i'll need to compute the asynfluid computation multiple times. However, sometimes the original call to asyn fluid will cause an error and each feature should be given nan. What is the best way around this?

**Comment by arnaudon** [comment]
This is a more general issue of precomputing certain graph quantities, that can be used accross several feature classes. 
We could have a preprocessing.py function with some of these, and lru_cache to not recompute them many time. I'll try things on that problem and report here.

**Comment by arnaudon** [comment]
Just pushed a working version for that, using lru_cache of functools.
