### ISSUE TITLE
node features are one hot encoded in benchmarks

### ISSUE THREAD

**Issue by peach-lucien** [ImperialCollegeLondon/hcga#49]
In the benchmark datasets the node labels and node features are one-hot encoded. The new version to extract these datasets simply just adds the node label (see DD dataset for example). To make it comparable with the other methods we must also binarize the benchmark datasets.

**Comment by arnaudon** [comment]
can you give more details on that? Not sure what to do

**Comment by peach-lucien** [comment]
so the original code that you shortened, that called the text files for each dataset. It took each feature and one-hot encoded it. 

So if we had 4 nodes and their features were 0,1,2,2

This would appear as a matrix:
[[1,0,0],[0,1,0],[0,0,1],[0,0,1]]

i.e. we just create a 4x3 matrix (4 nodes by 3 features).

I'll try and fix this...

**Comment by arnaudon** [comment]
just pushed it, please double check it is correct and close this issue, thanks!

**Comment by arnaudon** [comment]
pd.get_dummies() ;)
