### ISSUE TITLE
communities modularity fails

### ISSUE THREAD

**Issue by peach-lucien** [ImperialCollegeLondon/hcga#53]
Why does this feature fail so often? :dancers:

**Comment by arnaudon** [comment]
for which dataset? for me on enzymes and proteins and DD it seems to work. I've removed the rati thing that fails if there is only one community.

**Comment by peach-lucien** [comment]
with collab I was seeing some partitions where the second partition was just {0}

**Comment by arnaudon** [comment]
it was not modularity, it was other communities with outdated function and same feature_name...
